project:
  type: website

website:
  title: "Données émergentes"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:tutorials
      - sidebar:howto
      - sidebar:fundamentals
      - sidebar:reference

  sidebar:
    style: "docked"
    search: true
    - id: introduction
      title: "Introduction"
      contents:
        - section: "Introduction"
    - id: admin
      title: "Données administratives"
      contents:
        - administratives.qmd
        - administratives_exemples.qmd
      - section: "Données géolocalisées"
        contents:
          - geolocalized_data.qmd
      - section: "Analyse textuelle"
        contents:
          - textes.qmd
      - section: "Analyse d'images"
        contents:
          - images.qmd
      - section: "Nowcasting"
        contents:
          - series_temporelles.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/linogaliana/ensai-donnees-emergentes
          - text: Report a Bug
            url:  https://github.com/linogaliana/ensai-donnees-emergentes/issues
  page-navigation: true
  page-footer:
    left: "(c) 2022, Lino Galiana and Tom Seimandi"
    right:
      - icon: github
        href: https://github.com/linogaliana/ensai-donnees-emergentes
      - icon: twitter
        href: https://twitter.com/
  reader-mode: true
  repo-url: https://github.com/linogaliana/ensai-donnees-emergentes
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@linogaliana"
  open-graph: true


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

theme:
  light: flatly
  dark: darkly
